# Generated by Django 5.1.7 on 2025-04-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('job_category', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('working_hours', models.IntegerField()),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='worker_images/')),
                ('rating', models.FloatField(default=0.0)),
                ('aadhar', models.FileField(blank=True, null=True, upload_to='uploads/aadhar/')),
                ('proof', models.FileField(blank=True, null=True, upload_to='uploads/proof/')),
            ],
        ),
    ]
