# Generated by Django 5.1.7 on 2025-04-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_acc', '0002_initial'),
        ('worker_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='booking',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='worker_profiles.booking'),
            preserve_default=False,
        ),
    ]
