# Generated by Django 5.1.7 on 2025-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_acc', '0004_interviewrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewrequest',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
