# Generated by Django 5.1.7 on 2025-04-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0003_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
