# Generated by Django 5.1.7 on 2025-04-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0005_booking_payment_date_booking_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_reference',
        ),
    ]
