# Generated by Django 5.1.7 on 2025-04-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0007_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
    ]
