# Generated by Django 5.1.7 on 2025-04-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0008_remove_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='upi_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
