# Generated by Django 5.1.7 on 2025-04-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0011_booking_payment_done_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_done',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='upi_transaction_id',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('payment_done', models.BooleanField(default=False)),
                ('upi_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='worker_profiles.booking')),
            ],
        ),
    ]
