# Generated by Django 5.1.7 on 2025-04-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0012_remove_booking_payment_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
