# Generated by Django 5.1.7 on 2025-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0013_booking_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
