# Generated by Django 5.1.7 on 2025-04-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0014_booking_completed_at_booking_user_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_completed',
            new_name='worker_marked_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_confirmed',
        ),
        migrations.AddField(
            model_name='booking',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
