# Generated by Django 5.1.7 on 2025-04-26 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_acc', '0004_interviewrequest'),
        ('worker_profiles', '0015_rename_is_completed_booking_worker_marked_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('preferred_date1', models.DateField()),
                ('preferred_date2', models.DateField(blank=True, null=True)),
                ('preferred_date3', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_acc.workers')),
            ],
        ),
    ]
