# Generated by Django 5.1.7 on 2025-04-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0016_sitevisitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
