# Generated by Django 5.1.7 on 2025-04-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0017_sitevisitrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitrequest',
            name='confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisitrequest',
            name='worker_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
