# Generated by Django 5.1.7 on 2025-04-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0018_sitevisitrequest_confirmed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitrequest',
            name='worker_notified',
            field=models.BooleanField(default=False),
        ),
    ]
