# Generated by Django 5.1.7 on 2025-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0019_sitevisitrequest_worker_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitrequest',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
