# Generated by Django 5.1.7 on 2025-04-27 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0020_sitevisitrequest_payment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='site_visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='worker_profiles.sitevisitrequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='worker_profiles.booking'),
        ),
    ]
