# Generated by Django 5.1.7 on 2025-04-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0021_payment_site_visit_alter_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='site_visit',
        ),
        migrations.RemoveField(
            model_name='sitevisitrequest',
            name='payment_confirmed',
        ),
        migrations.RemoveField(
            model_name='sitevisitrequest',
            name='worker_notified',
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(
                null=True,  # <-- fixed here
                blank=True,  # <-- added blank=True for admin panel also
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payment',
                to='worker_profiles.booking'
            ),
        ),
        migrations.AlterField(
            model_name='sitevisitrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Accepted', 'Accepted'),
                    ('Rejected', 'Rejected'),
                    ('Completed', 'Completed')
                ],
                default='Pending',
                max_length=20
            ),
        ),
        migrations.CreateModel(
            name='SiteVisitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(
                    choices=[('Pending', 'Pending'), ('Paid', 'Paid')],
                    default='Pending',
                    max_length=20
                )),
                ('payment_done', models.BooleanField(default=False)),
                ('upi_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site_visit', models.OneToOneField(
                    null=True,  # <-- fixed here
                    blank=True,  # <-- added blank=True
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='site_visit_payment',
                    to='worker_profiles.sitevisitrequest'
                )),
            ],
        ),
    ]