# Generated by Django 5.1.7 on 2025-04-28 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0022_remove_payment_site_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='worker_profiles.booking'),
        ),
        migrations.AlterField(
            model_name='sitevisitpayment',
            name='site_visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_visit_payment', to='worker_profiles.sitevisitrequest'),
        ),
    ]
