# Generated by Django 5.1.7 on 2025-04-28 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_acc', '0004_interviewrequest'),
        ('worker_profiles', '0023_alter_payment_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='worker_acc.workers')),
            ],
        ),
    ]
