# Generated by Django 5.1.7 on 2025-04-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_acc', '0004_interviewrequest'),
        ('worker_profiles', '0024_workerbankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earning', 'Earning'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_acc.workers')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='worker_acc.workers')),
            ],
        ),
    ]
