# Generated by Django 5.1.7 on 2025-04-28 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_acc', '0004_interviewrequest'),
        ('worker_profiles', '0025_workertransactionhistory_workerwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerWithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_acc.workers')),
            ],
        ),
    ]
