# Generated by Django 5.1.7 on 2025-04-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0026_workerwithdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerwithdrawrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
