# Generated by Django 5.1.7 on 2025-04-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0027_workerwithdrawrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
