# Generated by Django 5.1.7 on 2025-04-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0028_payment_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitpayment',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
