# Generated by Django 5.1.7 on 2025-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0029_sitevisitpayment_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitrequest',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
