# Generated by Django 5.1.7 on 2025-05-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profiles', '0030_sitevisitrequest_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitrequest',
            name='worker_marked_completed',
            field=models.BooleanField(default=False),
        ),
    ]
